_BASE_: "base.yaml"

THRESH: 0.66
DEBUG: False

MODEL:
  TYPE: 'dualstreamunet'
  IN_CHANNELS: 28

DATASET:
  MODE: 'fusion'
  SENTINEL1_BANDS: ['VV']
  SENTINEL2_BANDS: ['B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B09', 'B10', 'B11', 'B12']